# - name: Add Wireguard PPA
#   become: true
#   apt_repository:
#     repo: ppa:wireguard/wireguard
#     state: present
#     update_cache: true
#   tags:
#     - wireguard

- name: Install Wireguard
  become: true
  apt:
    name:
      - wireguard
      - openresolv
      - iptables
      - net-tools
      - qrencode